#!/bin/bash
#===============================================================================
#
#   scripts/setup_usb_devices.sh
#
#   Configures udev rules + gpsd so the ELM327 OBD adapter and the GPS
#   dongle get stable, predictable paths (/dev/ttyELM327, /dev/ttyGPS)
#   and stop fighting over /dev/ttyACM*. Also:
#     - disables gpsd auto-hotplug (USBAUTO="false")
#     - pins gpsd to /dev/ttyGPS only
#     - updates experiments/obd-macos/*.py to use the stable symlink
#
#   Run:  sudo scripts/setup_usb_devices.sh
#   Idempotent: safe to re-run when the GPS is later plugged in.
#
#===============================================================================

set -e

RULES_FILE="/etc/udev/rules.d/99-pi-car.rules"
GPSD_DEFAULT="/etc/default/gpsd"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

G='\033[0;32m'; Y='\033[1;33m'; C='\033[0;36m'; R='\033[0;31m'; NC='\033[0m'
info() { echo -e "${C}==>${NC} $*"; }
ok()   { echo -e "${G}✓${NC} $*"; }
warn() { echo -e "${Y}!${NC} $*"; }
err()  { echo -e "${R}✗${NC} $*" >&2; }

if [ "$EUID" -ne 0 ]; then
    err "This script must be run with sudo."
    exit 1
fi

#-------------------------------------------------------------------------------
# 1. Discover plugged USB serial devices
#-------------------------------------------------------------------------------
info "Scanning USB serial devices..."
echo ""
printf "  %-18s %-12s %s\n" "DEVICE" "USB ID" "MODEL"
printf "  %-18s %-12s %s\n" "------" "------" "-----"

FOUND=0
for dev in /dev/ttyACM* /dev/ttyUSB*; do
    [ -e "$dev" ] || continue
    vid=$(udevadm info -q property -n "$dev" 2>/dev/null | awk -F= '/^ID_VENDOR_ID=/{print $2}')
    pid=$(udevadm info -q property -n "$dev" 2>/dev/null | awk -F= '/^ID_MODEL_ID=/{print $2}')
    model=$(udevadm info -q property -n "$dev" 2>/dev/null | awk -F= '/^ID_MODEL=/{print $2}' | tr '_' ' ')
    printf "  %-18s %-12s %s\n" "$dev" "${vid}:${pid}" "$model"
    FOUND=1
done

if [ "$FOUND" -eq 0 ]; then
    warn "No /dev/ttyACM* or /dev/ttyUSB* devices found. Plug the adapter(s) in and retry."
    exit 1
fi
echo ""

#-------------------------------------------------------------------------------
# 2. Build rules from user-selected devices
#-------------------------------------------------------------------------------
ask_device() {
    # $1 = human label, $2 = symlink basename -> prints a udev rule line
    local label="$1" symlink="$2" dev vid pid
    read -p "Which device is the ${label}? (e.g. /dev/ttyACM0, blank = skip): " dev
    [ -z "$dev" ] && return 0
    if [ ! -e "$dev" ]; then
        warn "${dev} not found, skipping ${label}."
        return 0
    fi
    vid=$(udevadm info -q property -n "$dev" 2>/dev/null | awk -F= '/^ID_VENDOR_ID=/{print $2}')
    pid=$(udevadm info -q property -n "$dev" 2>/dev/null | awk -F= '/^ID_MODEL_ID=/{print $2}')
    if [ -z "$vid" ] || [ -z "$pid" ]; then
        warn "Could not read USB IDs for ${dev}, skipping."
        return 0
    fi
    echo "SUBSYSTEM==\"tty\", ATTRS{idVendor}==\"${vid}\", ATTRS{idProduct}==\"${pid}\", SYMLINK+=\"${symlink}\", MODE=\"0660\", GROUP=\"dialout\""
}

OBD_RULE=$(ask_device "ELM327 / OBD-II adapter" "ttyELM327")
GPS_RULE=$(ask_device "GPS dongle"              "ttyGPS")

if [ -z "$OBD_RULE" ] && [ -z "$GPS_RULE" ]; then
    warn "Nothing selected, exiting without changes."
    exit 0
fi

#-------------------------------------------------------------------------------
# 3. Merge into the rules file (preserve whatever else is there)
#-------------------------------------------------------------------------------
info "Writing ${RULES_FILE} ..."
TMP=$(mktemp)
{
    echo "# Generated by pi-car scripts/setup_usb_devices.sh"
    [ -n "$OBD_RULE" ] && echo "$OBD_RULE"
    [ -n "$GPS_RULE" ] && echo "$GPS_RULE"
} > "$TMP"

# If the file already exists, keep any unrelated rules from it
if [ -f "$RULES_FILE" ]; then
    grep -Ev 'SYMLINK\+="ttyELM327"|SYMLINK\+="ttyGPS"|^# Generated by pi-car' "$RULES_FILE" >> "$TMP" || true
fi
install -m 0644 "$TMP" "$RULES_FILE"
rm -f "$TMP"

ok "Rules written:"
sed 's/^/    /' "$RULES_FILE"

info "Reloading udev..."
udevadm control --reload-rules
udevadm trigger --subsystem-match=tty

#-------------------------------------------------------------------------------
# 4. Tame gpsd so it stops grabbing random ACM ports
#-------------------------------------------------------------------------------
if [ -f "$GPSD_DEFAULT" ]; then
    info "Configuring ${GPSD_DEFAULT} (USBAUTO=false, DEVICES=/dev/ttyGPS)..."
    [ -f "${GPSD_DEFAULT}.pi-car.bak" ] || cp "$GPSD_DEFAULT" "${GPSD_DEFAULT}.pi-car.bak"

    if grep -q '^USBAUTO=' "$GPSD_DEFAULT"; then
        sed -i 's|^USBAUTO=.*|USBAUTO="false"|' "$GPSD_DEFAULT"
    else
        echo 'USBAUTO="false"' >> "$GPSD_DEFAULT"
    fi

    if grep -q '^DEVICES=' "$GPSD_DEFAULT"; then
        sed -i 's|^DEVICES=.*|DEVICES="/dev/ttyGPS"|' "$GPSD_DEFAULT"
    else
        echo 'DEVICES="/dev/ttyGPS"' >> "$GPSD_DEFAULT"
    fi
    ok "gpsd pinned to /dev/ttyGPS (backup at ${GPSD_DEFAULT}.pi-car.bak)"
else
    warn "${GPSD_DEFAULT} not found — skipping gpsd config"
fi

#-------------------------------------------------------------------------------
# 5. Verify the symlinks came up
#-------------------------------------------------------------------------------
echo ""
info "Verifying symlinks..."
if [ -n "$OBD_RULE" ]; then
    if [ -L /dev/ttyELM327 ]; then
        ok "/dev/ttyELM327 -> $(readlink /dev/ttyELM327)"
    else
        warn "/dev/ttyELM327 not present yet — unplug/replug the adapter."
    fi
fi
if [ -n "$GPS_RULE" ]; then
    if [ -L /dev/ttyGPS ]; then
        ok "/dev/ttyGPS -> $(readlink /dev/ttyGPS)"
    else
        warn "/dev/ttyGPS not present yet — unplug/replug the GPS."
    fi
fi

#-------------------------------------------------------------------------------
# 6. Update experiment scripts' PORT variable (optional)
#-------------------------------------------------------------------------------
if [ -n "$OBD_RULE" ] && [ -d "${REPO_ROOT}/experiments/obd-macos" ]; then
    echo ""
    read -p "Update experiments/obd-macos/*.py PORT to /dev/ttyELM327? [Y/n] " reply
    reply=${reply:-Y}
    if [[ "$reply" =~ ^[Yy]$ ]]; then
        for f in "${REPO_ROOT}/experiments/obd-macos"/*.py; do
            [ -f "$f" ] || continue
            sed -i 's|^PORT = .*|PORT = "/dev/ttyELM327"|' "$f"
        done
        ok "PORT set to /dev/ttyELM327 in experiment scripts"
    fi
fi

#-------------------------------------------------------------------------------
# 7. Offer to stop gpsd so the OBD port is free
#-------------------------------------------------------------------------------
if systemctl is-active --quiet gpsd 2>/dev/null || systemctl is-active --quiet gpsd.socket 2>/dev/null; then
    echo ""
    read -p "Stop gpsd now so the OBD test can open the port? [Y/n] " reply
    reply=${reply:-Y}
    if [[ "$reply" =~ ^[Yy]$ ]]; then
        systemctl stop gpsd gpsd.socket 2>/dev/null || true
        ok "gpsd stopped (restart later with: sudo systemctl start gpsd.socket)"
    fi
fi

#-------------------------------------------------------------------------------
# Done
#-------------------------------------------------------------------------------
echo ""
ok "Setup complete."
echo ""
echo "Next:"
echo "    cd ${REPO_ROOT}/experiments/obd-macos"
echo "    source venv/bin/activate"
echo "    python3 obd_test_connection.py"
